services:
  - type: web
    name: rn-ota-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false

databases:
  - name: mongodb
    plan: free
    ipAllowList: []
